### ISSUE TITLE
Plugin not loading 

### ISSUE THREAD

**Issue by ConsoleGods** [NedHuman/DupeDetect#1]
Plugin isn’t loading here is the error log https://mclo.gs/hlk6oon

**Comment by NedHuman** [comment]
oops, wait I'll fix

**Comment by NedHuman** [comment]
Issue resolved, it was a capitalisation error (dupeDetect and dupedetect), issue has been resolved now and a new version has been uploaded to spigotmc
thanks for reporting the issue
